AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an ACM certificate in us-east-1 and a CloudFront distribution with up to 5 origins and behavior suffixes.

Parameters:
  DomainName:
    Type: String
    Description: The primary domain name for the ACM certificate.
  SubjectAlternativeNames:
    Type: CommaDelimitedList
    Description: Additional domain names for the ACM certificate.
    Default: ""

  defaultOriginDomain:
    Type: String
    Description: The default origin domain name (S3 bucket or custom domain).


Resources:
  Certificate:
    Type: "AWS::CertificateManager::Certificate"
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS
      SubjectAlternativeNames: !Ref SubjectAlternativeNames
      Tags:
        - Key: Name
          Value: !Ref DomainName

  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: defaultOrigin
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        Origins:
          - Id: defaultOrigin
            DomainName: !Ref defaultOriginDomain
            OriginPath: "*"
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
      
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          SslSupportMethod: sni-only


Outputs:
  CloudFrontDistributionId:
    Description: The ID of the CloudFront distribution.
    Value: !Ref CloudFrontDistribution
  CloudFrontDomainName:
    Description: The domain name of the CloudFront distribution.
    Value: !GetAtt CloudFrontDistribution.DomainName
